name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build and Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/riot-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/riot-frontend:latest

            # Stop old containers
            docker stop riot-backend || true && docker rm riot-backend || true
            docker stop riot-frontend || true && docker rm riot-frontend || true

            # Start new ones
            docker run -d --name riot-backend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/riot-backend:latest
            docker run -d --name riot-frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/riot-frontend:latest
          EOF
